- packages/sanity-studio/README.md
- packages/sanity-studio/src/components/PathnameFieldComponent.tsx
- packages/sanity-studio/src/types.ts
This PR adds the option to `pathname` fields to prevent folders from being unlocked and edited per document type.
This is useful for documents that are initialised with a particular directory, such as Products, Factsheets, Blog articles, etc, where we don't want to allow the parent folder to be changed.
This PR makes use of the existing `options` object on the pathname schema definition. It adds a new `folder` key, which takes an object with key/value `canUnlock: boolean`. This will initialise to `true` if not set in the document schema.
```
definePathname({ name: 'pathname', options: { folder: { canUnlock: false } } }),
```
When `false`, the field is set to `disabled`, a padlock icon replaces the pencil icon, and the title is changed to explain that it is locked and cannot be changed. …
> feat: allow documents to prevent folder from unlocking and being edited

- packages/sanity-studio/package.json
- packages/sanity-web/package.json
Heya 👋 
We've setup your `@tinloof/sanity-kit` over at https://github.com/sanity-io/visual-editing/tree/main/apps/next-with-i18n to ensure that we don't accidentally introduce breaking changes to how you customize `@sanity/presentation` :) 
That's how we noticed that when `renovatebot` created a [PR bumping your package](https://github.com/sanity-io/visual-editing/pull/1415) it didn't succeed in grabbing your changelogs.
In this PR I'm adding the metadata fields needed for tools like `renovatebot`, `dependabot` and such to find your release notes 🙇 
Great work on your kit btw, we're huge fans 💖
> fix: add `repository` field to `package.json`

- .changeset/rare-hairs-prove.md
- apps/studio/sanity.config.ts
- apps/studio/schemas/author.ts
- apps/studio/schemas/index.ts
- apps/studio/schemas/post.ts
- packages/sanity-studio/src/plugins/navigator/components/Header.tsx
This PR fixes https://github.com/tinloof/sanity-kit/issues/22.
`definePathname` initialValue is now used when creating a new document from the root of the pages navigator.
This also seems to fix https://github.com/tinloof/sanity-kit/issues/36 based on my tests. The initialValue is now used on document creation so the `canUnlock` option works as expected.
> Fix definePathname inititalValue in pagesNavigator

- .changeset/blue-numbers-beam.md
- packages/sanity-studio/src/components/PathnameFieldComponent.tsx
https://github.com/tinloof/sanity-kit/assets/15708264/7a70928c-4c15-455a-81fc-023f05c0c4ff
now, `validation` will show in the pathname input in sanity studio
```
definePathname({
name: "pathname",
initialValue: {
current: '/blog/',
},
options: {
folder: {
canUnlock: false,
},
i18n: {
enabled: true,
defaultLocaleId: config.i18n.defaultLocaleId,
},
},
validation: rule => rule.custom((pathname) => {
return !!pathname?.current?.replace('/blog/', '').length || "Required";
}),
})
```
> Add validation UI to input

- .changeset/tiny-phones-fly.md
- packages/sanity-studio/src/components/PathnameFieldComponent.tsx
- packages/sanity-studio/src/hooks/usePathnameContext.ts
- packages/sanity-studio/src/hooks/usePathnamePrefix.ts
- packages/sanity-studio/src/types.ts
The pathname field always shows the current hostname origin as the prefix, e.g. `localhost:3333`
However, some websites are hosted on separate subdomains, or need different prefixes based on document types or values.
This PR adds the ability to specify the prefix in the pathname field definition, using `options.prefix`.
```js
definePathname({
name: 'pathname', 
options: { prefix: 'https://google.com' },
}),
```
It can also be defined as a function that returns a `string` or a `Promise<string>`. This function will receive the current document as well as the studio context as parameters:
```js
definePathname({
name: 'pathname', 
options: { prefix: (document, context) => 'https://google.com' },
}),
```
The context includes a client, project ID, dataset, schema and the currentUser
To maintain …
> feat: allow pathname field to specify prefix

- packages/sanity-studio/src/hooks/usePathnamePrefix.ts
Hey,
First of all, kudos on releasing this tool to the public, excellent stuff!
In #51, an option was added to set a custom prefix for the pathname field. This however removed the default prefix `window.location.origin`, which I believe was unintended since it still makes for a sensible default. This PR adds that back as the default.
> fix(pathname): add back `window.location.origin` as default pathname prefix

- packages/sanity-studio/src/plugins/navigator/components/Preview.tsx
I was getting the following error when trying to access some of my pages inside folders:
```js
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `PreviewMedia`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `PreviewMedia`.
at createFiberFromTypeAndProps (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.3_@babel+core@7.24.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom-experimental/cjs/react-dom.development.js:28366:17)
at createFiberFromElement …
```
> Fix PreviewMedia component crashing when media is an object

- .changeset/modern-frogs-give.md
- packages/sanity-studio/src/components/PathnameFieldComponent.tsx
- packages/sanity-studio/src/plugins/navigator/components/List.tsx
- packages/sanity-studio/src/plugins/navigator/context/index.tsx
- packages/sanity-studio/src/types.ts
- packages/sanity-web/src/types.ts
- packages/sanity-web/src/utils/urls/index.ts
Partially related to my proposed changes in #57 
We're using next-intl for our frontends using which we can have localized pathnames. Thus, a document that is stored in Sanity with a pathname of `/employees/marcus-forsberg` may be rewritten to `/sv/personal/marcus-forsberg`. Or, as in #57, we may have singleton document types that aren't translated at all through Sanity but that will have different pathnames per locale in the frontend.
This PR aims to solve this use case by allowing a custom `localizePathname` method to be passed both to the Navigator and to `definePathname`. In addition, the Navigator now sends through a `fallbackLocaleId` which is set to the currently filtered locale. This allows us to correctly rewrite the pathnames of documents that are not localized in Sanity to …
> feat: allow using custom localizePathname function

- .changeset/slimy-keys-check.md
- packages/sanity-studio/README.md
- packages/sanity-studio/src/plugins/navigator/context/index.tsx
- packages/sanity-studio/src/types.ts
Here's a use case I don't necessarily know if you wish to support but that I hope you'll consider. 😊 
For our current project, we have a mix of localized and non-localized page types which we want to be able to access from the navigator. Since they all have a `pathname` field they automatically show up in the navigator, up until `i18n` is enabled at which point the list is filtered by the selected locale, causing the page types that don't have a `locale` field at all to disappear and become inaccessible. 
This PR adds a `requireLocale` option which can be set to `false` in order to get the non-localized page types to show up in the list regardless of the filtered locale.
For example, take an `employee` type which maps to an employee profile page on the front-end, which we want editors to …
> feat: add requireLocale option to allow working with non-translatable page types even with i18n enabled

- .changeset/two-ears-listen.md
- packages/sanity-studio/README.md
- packages/sanity-studio/package.json
- packages/sanity-studio/src/components/PathnameFieldComponent.tsx
- packages/sanity-studio/src/types.ts
- pnpm-lock.yaml
This PR adds an optional `autoNavigate` option to the pathname field. Setting it to true will result in the "Preview" button being hidden and the Presentation tool automatically navigating to the new pathname as it changes (with a 1 second debounce to avoid spamming the frontend/API). You can see the pathname changing in the Presentation iframe in the video below:
https://github.com/tinloof/sanity-kit/assets/1009069/ee21347b-5356-403e-a7f8-d7eb7ed7fea5
> feat(pathname): add autoNavigate option to hide the "Preview" button and automatically navigate as the pathname changes

- .changeset/metal-experts-stare.md
- packages/sanity-studio/README.md
- packages/sanity-studio/package.json
- packages/sanity-studio/src/components/PathnameFieldComponent.tsx
- packages/sanity-studio/src/hooks/useAsync.ts
- packages/sanity-studio/src/types.ts
- pnpm-lock.yaml
Fixes #19 
This PR adds support for the `source` field, like on the native Slug type. When set, there will be a button to generate the pathname:
Any existing folder will remain untouched, as only the final segment is updated.
As part of this I updated the `PathnameParams` type so that it no longer inherits the `maxLength` and `slugify` properties from `SlugOptions` since these aren't supported.
> feat(pathname): implement "source" option and "Generate" button

- .changeset/wise-kids-dream.md
- packages/sanity-studio/README.md
- packages/sanity-studio/src/plugins/navigator/components/DefaultPagesNavigator.tsx
- packages/sanity-studio/src/plugins/navigator/components/List.tsx
- packages/sanity-studio/src/plugins/navigator/context/index.tsx
- packages/sanity-studio/src/plugins/navigator/index.ts
- packages/sanity-studio/src/types.ts
This PR adds a `folders` option to the plugin which can be used to change how individual folders render in the navigator, specifically their title and/or icon.
This can be used to make it a little easier to find specific folders, for example the /products folder could have the same icon as the Products schema type, and the /news folder could have a newspaper icon.
Changing the title can be useful if the slug doesn't match the name of the schema type: eg. the `article` schema type may live under the `/news` prefix, but the editors are used to referring to "Articles" so it's easier for them to look for the "Articles" folder than the automatically titled "News" folder. It's also useful for localized sites using a [custom `localizePathname`](https://github.com/tinloof/sanity-kit/pull/58) …
> feat: add ability to set custom icons and titles for folders in the navigator

- .changeset/fluffy-phones-explain.md
- packages/sanity-studio/src/components/PathnameFieldComponent.tsx
As [suggested by @Jamiewarb](https://github.com/tinloof/sanity-kit/issues/19#issuecomment-2066934062), this PR hides the Preview button entirely when outside of the Presentation tool. Previously it would still be there but always disabled since it has no function outside of the Presentation tool. When working in the Structure tool I think it makes the most sense to not have that dead button there at all.
> fix(pathname): hide Preview button when outside of Presentation tool (eg. in Structure tool)

- .changeset/fast-dragons-count.md
- packages/sanity-studio/src/plugins/navigator/components/List.tsx
- packages/sanity-studio/src/types.ts
#66 contained a mistake causing custom folder titles to not be applied in the navigator when i18n is enabled. This fixes that by looking at the original pathname instead of the localized one (same as it already did for the icons).
Also includes the ability to use a callback function to generate the folder title based on the selected locale.
> feat: properly render custom folder titles with i18n enabled + add ability to localize folder titles

- .changeset/twenty-books-promise.md
- packages/sanity-studio/src/plugins/navigator/components/Preview.tsx
There's an issue with the document preview titles in the navigator.
The titles end up always being generated from the pathname, regardless of a document's actual title.
This is problematic, for example, if a page's title and pathname differ:
It's also an issue for non-English titles, for example:
This PR fixes the preview logic so that the correct titles are always shown:
This should make it clear to editors which page is which, even if the pathname differs or if there are special characters or capitalized characters in the title.
I used these components in Sanity's repo as reference for this change:
- https://github.com/sanity-io/sanity/blob/14530aa3b0072c70b8c9cf4a5182af78ec975f81/packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItemPrevi …
> fix: render correct preview titles

- .changeset/silly-meals-exercise.md
- packages/sanity-studio/README.md
- packages/sanity-studio/src/utils/index.ts
- packages/sanity-studio/src/utils/localizedItem.ts
Added `localizedItem` to aide with the organization of i18n Sanity structures to the `@tinloof/sanity-studio` package
Updated the README under the `sanity-studio` package to reflect the changes and let users know how they can add it to their projects
> localizedItem added

- .changeset/red-trains-behave.md
- packages/sanity-studio/README.md
- packages/sanity-studio/package.json
- packages/sanity-studio/src/plugins/disableCreation/actions.ts
- packages/sanity-studio/src/plugins/disableCreation/index.ts
- packages/sanity-studio/src/plugins/disableCreation/templates.ts
- packages/sanity-studio/src/plugins/disableCreation/types.ts
- packages/sanity-studio/src/plugins/disableCreation/utils.ts
- packages/sanity-studio/src/plugins/index.ts
Adds the disable creation plugin which disables the creation of documents when the option `disableCreation` is set to true
Also downgrades `@sanity/document-internationalization` from 3.2.1. to 3.2.0 in order to fix the following [issue](https://github.com/tinloof/sanity-kit/issues/112). Another [issue ](https://github.com/sanity-io/document-internationalization/issues/199) was open on the `@sanity/document-internationalization` repo too.
> Disable creation plugin, document-internationalization downgrade

- .changeset/six-lies-laugh.md
- packages/sanity-studio/README.md
- packages/sanity-studio/src/components/index.ts
- packages/sanity-studio/src/components/input-with-characters-count.tsx
Adds custom component which shows a characters count of a string input with min and max length values.
Helps out with the following [issue](https://github.com/tinloof/sanity-kit/issues/83)
> Input with characters count component

- .changeset/loud-horses-rush.md
- packages/sanity-studio/src/plugins/navigator/utils/index.tsx
Removed query and variables as deps, they were added in this [PR](https://github.com/tinloof/sanity-kit/commit/003dea9d283591f0ec637e11ec7c5185170e702d#diff-3097fd8ffd357e156f7a0ee7bd66994de46bcced867919e18e8615d44c6c60d7)
With them there the pages navigator on the left where all the pages are listed is stuck in a loading state, removing them and not included like before the referenced PR fixes it
> Remove query and variables from deps

- .changeset/olive-tomatoes-admire.md
- packages/sanity-studio/README.md
- packages/sanity-studio/src/components/IconSelectComponent.tsx
- packages/sanity-studio/src/types.ts
Adds background color option to the icon schema in cases of where users have light colored icons which cannot been seen on the current default white background
In cases of the below screenshot where the user has a sanity studio embedded into a Next.js app with tailwindcss the following happens to images. Image container and image styles have been updated to override those styles.
> Background color option and tailwindcss img styles override

- .changeset/tasty-planets-press.md
- packages/sanity-studio/README.md
- packages/sanity-studio/src/utils/localizedItem.ts
Adds an icon option to `localizedItem` to assist with readability of folder structure in Sanity
Currently it default to the Sanity folder icon and in a project with a large amount of documents, those who use the utility `localizedItem` to be displayed in the structure stand out since they are all the same.
At glance users you cannot quickly tell what it is without reading the name.
> icon option in localizedItem, changeset and readme updated

- .changeset/six-queens-poke.md
- packages/sanity-studio/src/utils/definePathname.ts
Current uniqueness test deems /blog and /blog/ to be two different pages
This caused the blog page on Watershed to crash when someone published a new post with the pathname /blog/ without giving them an error.
/blog/ was there as it was set as the initial value.
> definePathname uniqueness

- .changeset/twelve-carrots-relate.md
- packages/sanity-studio/src/plugins/navigator/components/List.tsx
https://github.com/tinloof/sanity-kit/releases/tag/%40tinloof%2Fsanity-studio%401.7.4 adds a import bug
Seif added a fix for the pages navigator list component to improve performance and imported various things from @sanity/presentation
In the same package update, Cory updated the Sanity packages around the repo and one of the updates included updating things from sanity/presentation instead of @sanity/presentation
> sanity presentation import fix

- .changeset/proud-spies-smoke.md
- packages/sanity-studio/src/plugins/navigator/components/Header.tsx
Currently when creating a document with a pathname intial value set will be override if created within a folder.
Set `getPathname` so it priorityizes the initial value of the schmea
> initial value over current folder

- .changeset/rich-zoos-bake.md
- packages/sanity-studio/src/components/IconSelectComponent.tsx
- Removed background which gets applied on icon hover, slightly covers other icons next to it
- Moved icon grid responsiveness from the Sanity props way to container media queries
Internal issue - [TIN-2771: IconSelectComponent styles update](https://linear.app/tinloof/issue/TIN-2771/iconselectcomponent-styles-update)
> styles update, more responsive
